name: 'Package Upload'
description: 'Uploads a package to Chassy Index'
author: 'Chassy'

inputs:
  artifact:
    description: 'The path to the artifact to Upload'
    required: true
  type:
    description: 'The of artifact we want to upload. Eg: CONTAINER, FILE, ARCHIVE, RFSIMAGE, FIRMWARE'
    required: true
  architecture:
    description: 'The target chipset architecture, eg: AMD64, ARM64'
    required: false
  osID:
    description: 'the OS this targets, ie Ubuntu, ThreadX'
    required: false
  osVersion:
    description: 'the version of OS, ie 22.04'
    required: false
  # note: may have to add api base url or chassy token here, but we will ignore that until req'd    

outputs:
  status:
    description: 'A log/status message denoting the success of the upload'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.architecture }}
    - ${{ inputs.os }}
    - ${{ inputs.version }}
    - ${{ inputs.type }}
    - ${{ inputs.class }}
    - ${{ inputs.mode }}
    - ${{ inputs.dryrun }}

